name: NoSpam
main: net.simpvp.NoSpam.NoSpam
version: 3
author: C4K3.org
description: Automutes noisy people
commands:
  mute:
    description: Mutes a player
    usage: Error. Please report at http://simpvp.net/forum
  unmute:
    description: Unmutes a player
    usage: Error. Please report at http://simpvp.net/forum
  amimuted:
    description: Let's players know if they're muted or not
    usage: Error. Please report at http://simpvp.net/forum
